#ifndef _LANGUAGE_H
#define _LANGUAGE_H

#define MAX_STR_LEN	30

enum brewStringIndexEnum {
	STR_BREWOMATIC,
	STR_FAILURE,
	STR_MAIN_MENU,
	STR_BREWING_MENU,
	STR_BACK,
	STR_IDLE,
	STR_BREWING,
	STR_STOP,
	STR_MODE,
	STR_ADJUST_TEMP_OFFSET,
	STR_STARTING,
	STR_START_BREWING,
	STR_TEMPERATURE,
	STR_TARGET_TEMP,
	STR_STEP,
	STR_DURATION,
	STR_WAIT_TEMP,
	STR_MISSING_MAIN,
	STR_ERROR,
	STR_READY,
	STR_TEMP_FAILED,
	STR_MANUAL_MODE,
	STR_ENABLE_PUMP,
	STR_DISABLE_PUMP,
	STR_HEATING,
	STR_MASHING,
	STR_BOILING,
	STR_COOLING,
	STR_PRESS_OK,
	STR_INSERT_MALT,
	STR_REMOVE_MALT,
	STR_SETUP_COOLER,
	STR_BREWING_DONE,
	STR_TEMP_REACHED,
	STR_NO_SD_CARD,
	STR_BROWSE_SD_CARD,
	STR_INVALID_RECIPE,
	/* Always last member of enum */
	STR_COUNT
};

typedef char brewStringIndex;

const char *getString(brewStringIndex strIdx);

void getStringInBuffer(brewStringIndex strIdx, char *buf, int len);

#endif
